services:
  pihole:
    container_name: pihole
    image: wittebol/pihole-unbound:latest
    hostname: ${HOSTNAME}
    domainname: ${DOMAIN_NAME}
    ports:
      - 44300:443/tcp
      - 53:53/tcp
      - 53:53/udp
      - ${PIHOLE_WEBPORT:-80}:80/tcp #Allows use of different port to access pihole web interface when other docker containers use port 80
      - 5335:5335/tcp # Uncomment to enable unbound access on local server
     # - 22/tcp # Uncomment to enable SSH
    environment:
      #- FTLCONF_LOCAL_IPV4=${FTLCONF_LOCAL_IPV4}
      #- FTLCONF_LOCAL_IPV6=${FTLCONF_LOCAL_IPV6}
      - TZ=${TZ:-UTC}
      - FTLCONF_webserver_api_password=${WEBPASSWORD}
      - FTLCONF_dns_revServers=${REV_SERVER:-false},${REV_SERVER_CIDR},${REV_SERVER_TARGET},${REV_SERVER_DOMAIN}
      - FTLCONF_dns_upstreams=127.0.0.1#5335
      - FTLCONF_dns_dnssec=true
      - FTLCONF_dns_listeningMode=single
      - FTLCONF_misc_etc_dnsmasq_d=true
    volumes:
      - ./etc-pihole:/etc/pihole:rw
      - ./etc-dnsmasq.d:/etc/dnsmasq.d:rw
    restart: unless-stopped
    networks:
      pihole-unbound:

networks:
  pihole-unbound:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_ipv6: "true"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: "192.168.100.0/24"
        - subnet: "fd00::/64" 
